[project]
name = "pysequence-api"
version = "0.1.0"
description = "Unofficial FastAPI REST server for the GetSequence SDK"
authors = [
    {name = "Christian De Leon", email = "christian@deleon.me"}
]
license = {text = "MIT"}
requires-python = ">=3.11"
dependencies = [
    "fastapi (>=0.128.8,<0.129.0)",
    "uvicorn (>=0.40.0,<0.41.0)",
]

[tool.poetry]
packages = [{include = "pysequence_api", from = "src"}]

[tool.poetry.dependencies]
pysequence-sdk = {path = "../pysequence-sdk", develop = true}

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
