[project]
name = "pysequence-client"
version = "0.3.0"
description = "Unofficial Python client for the GetSequence API server"
authors = [
    {name = "Christian De Leon", email = "christian@deleon.me"}
]
license = {text = "MIT"}
requires-python = ">=3.11"
dependencies = [
    "httpx (>=0.28.1,<0.29.0)",
    "pydantic (>=2.12.5,<3.0.0)",
]
readme = "README.md"

[project.urls]
Homepage = "https://github.com/christian-deleon/PySequence"
Repository = "https://github.com/christian-deleon/PySequence"
Documentation = "https://github.com/christian-deleon/PySequence/blob/main/docs/http-client.md"
Changelog = "https://github.com/christian-deleon/PySequence/releases"

[tool.poetry]
packages = [{include = "pysequence_client", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
